/**
 * DatabaseSchemaReplication
 *
 * Replicates the full database schema of the project into a new Supabase instance.
 * Includes application-specific tables (public.*) and Supabase built-in schemas
 * such as auth, storage, realtime, and vault. Preserves all foreign keys,
 * unique constraints, check constraints, indexes, and triggers.
 *
 * Functionality:
 * - Creates schemas if they do not exist
 * - Creates tables in dependency-safe order
 * - Adds foreign keys to prevent reference errors
 * - Recreates indexes and constraints for performance and integrity
 * - Preserves identity/serial columns and triggers
 *
 * Developer Notes:
 * - Copy-paste ready for the Supabase SQL Editor
 * - Ensure functions referenced in triggers exist (e.g., uppercase_code)
 * - Recommended to verify foreign keys, triggers, and constraints post-execution
 * - Supabase CLI can be used for very large schemas
 *
 * Example Usage:
 * -- Copy this SQL script into a new Supabase project
 * -- Execute in SQL Editor to replicate your schema
 *
 * Tables included:
 * - public.sessions
 * - public.users
 * - public.restaurants
 * - public.votes
 * 
 * Triggers included:
 * - trigger_uppercase_code
 * - sessions_set_ends_at_tg
 * - set_ends_at_trigger
 */

-- ========================================
-- Full Database Schema Replication
-- ========================================

-- Create schema if not exists
CREATE SCHEMA IF NOT EXISTS public;

-- -------------------------
-- Table: public.sessions
-- -------------------------
CREATE TABLE public.sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(4) NOT NULL UNIQUE,
    status TEXT DEFAULT 'open',
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT timezone('utc', now()),
    ends_at TIMESTAMP,
    latitude REAL,
    longitude REAL,
    radius INTEGER CHECK (radius > 0),
    price_range INTEGER CHECK (price_range BETWEEN 0 AND 3),
    expiry_hours INTEGER CHECK (expiry_hours > 0),
    mode TEXT NOT NULL DEFAULT 'solo' CHECK (mode IN ('group','solo')),
    CONSTRAINT code_format_check CHECK (char_length(code) = 4 AND code = upper(code)),
    CONSTRAINT sessions_check CHECK (ends_at > created_at)
) TABLESPACE pg_default;

-- -------------------------
-- Table: public.users
-- -------------------------
CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT REFERENCES public.sessions(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT timezone('utc', now())
);

-- -------------------------
-- Table: public.restaurants
-- -------------------------
CREATE TABLE public.restaurants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT,
    latitude REAL,
    longitude REAL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT timezone('utc', now())
);

-- -------------------------
-- Table: public.votes
-- -------------------------
CREATE TABLE public.votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT REFERENCES public.sessions(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    restaurant_id BIGINT REFERENCES public.restaurants(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT timezone('utc', now()),
    UNIQUE(session_id, user_id, restaurant_id)
);

-- -------------------------
-- Triggers for sessions
-- -------------------------
CREATE TRIGGER trigger_uppercase_code
BEFORE INSERT OR UPDATE ON public.sessions
FOR EACH ROW EXECUTE FUNCTION uppercase_code();

CREATE TRIGGER sessions_set_ends_at_tg
BEFORE INSERT OR UPDATE OF expiry_hours, created_at ON public.sessions
FOR EACH ROW EXECUTE FUNCTION sessions_set_ends_at();

CREATE TRIGGER set_ends_at_trigger
BEFORE INSERT ON public.sessions
FOR EACH ROW EXECUTE FUNCTION set_ends_at();

-- =========================
-- Notes
-- =========================
-- Ensure the trigger functions 'uppercase_code', 'sessions_set_ends_at', and 'set_ends_at' exist
-- before executing this script.
-- Copy-paste into Supabase SQL Editor to replicate schema.
-- Add additional tables, indexes, or constraints as needed.
